name: Java CI with Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # إعداد الجافا (يجب استخدام إصدار 8 لـ 1.8.9)
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # إعطاء صلاحية التنفيذ لملف gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # عملية التجميع وتحويل الكود لملف .jar
    - name: Build with Gradle
      run: ./gradlew build

    # رفع ملف الـ .jar الناتج كملف قابل للتحميل
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: KillAura
        path: build/libs/*.jar
